# Generated by Django 4.2.1 on 2023-06-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='pic4',
            new_name='pic',
        ),
    ]
